server:
  port: 8080
spring:
  application:
    name: usercoding
  datasource:
    url: 'jdbc:postgresql://localhost:5432/usercoding?ApplicationName=usercoding'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
#        default_schema: public
    open-in-view: false
    show-sql: true
  main:
    allow-circular-references: true



  flyway:
    installed-by: 'Kevin Janvier Chinabalire'
    baseline-on-migrate: true
#    locations: 'classpath:/db/migration/public'

logging:
  level:
    org:
      springframework: info